[package]
name = "assext"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.24"
imageproc = "0.23"
egui = "0.24"
eframe = "0.24"
walkdir = "2.4"
anyhow = "1.0"
rusttype = "0.9"